# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6da038e05d06a8f91d7747c91f76f4e16bc78650c0eb4a9a0652e8d4c9b09145f740790701ed992ece9eb98bcef8c7fb160cbf0fd38ec0d442d8c4dc19503d

test:
  secret_key_base: 58241861b1eb6fbe7f90991285244835818e25b38aff5f9e3f9bc21d750fc2d7a10be6154c8352149f42d50e17c37224e40ed964c0b9cc00be28110a9fd109b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
